project:
  type: website
  output-dir: docs

website:
  title: "Surveillance Dengue Variants in Senegal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Background
      - href: result.qmd
        text: Results
format:
  html:
    theme:
      light: flaty
      dark: darkly
    css: styles.css
    toc: true



